name: General
description: General discussion about the Strapi OIDC plugin
body:
  - type: markdown
    attributes:
      value: |
        Discuss anything related to the plugin, share tips, or ask for advice.
  - type: textarea
    id: body
    attributes:
      label: Discussion
      description: What's on your mind?
    validations:
      required: true
